# Generated by Django 4.1.4 on 2023-05-17 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(null=True)),
                ("specialty", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Appoinment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("10-10:30", "10-10:30"),
                            ("10:30-11", "10:30-11"),
                            ("11-11:30", "11-11:30"),
                            ("11:30-12", "11:30-12"),
                            ("12-12:30", "12-12:30"),
                            ("12:30-1", "12:30-1"),
                            ("1-1:30", "1-1:30"),
                            ("1:30-2", "1:30-2"),
                        ],
                        default=None,
                        max_length=15,
                    ),
                ),
                ("booked", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.doctor",
                    ),
                ),
            ],
        ),
    ]
