# Generated by Django 4.1.4 on 2023-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appoinment_duration_alter_appoinment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appoinment",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "1 hour"),
                ],
                default=15,
            ),
        ),
    ]
