# Generated by Django 4.1.4 on 2023-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appoinment_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="end_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
