# Generated by Django 4.1.4 on 2023-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_appoinment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appoinment",
            name="availability",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("UNAVAILABLE", "Unavailable")],
                default="AVAILABLE",
                max_length=12,
            ),
        ),
    ]
